version: '3'

services:
  postgres:
    container_name: cards_postgres
    image: postgres:18.1
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=training-cards
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./initSchema.sql:/docker-entrypoint-initdb.d/initSchema.sql